name: aventura

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^5.2.7
  cupertino_icons: ^0.1.2
  flutter_local_notifications: ^0.6.0
  path_provider: ^0.5.0+1
  carousel_pro: ^1.0.0
  provider: ^3.1.0+1
  intl: ^0.16.0
  location: ^2.3.5
  geolocator: ^5.1.5
  cached_network_image: ^1.1.3
  firebase_auth: ^0.14.0+8
  cloud_firestore: ^0.12.10
  firebase_storage: ^3.0.8
  permission_handler: ^4.0.0
  geocoder: ^0.2.1
  google_maps_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Multilingual_Hand
      fonts:
        - asset: fonts/Multilingual-Hand.ttf

    - family: Wooa
      fonts:
        - asset: fonts/wooa.ttf
